language: go

go:
  - 1.9

script:
  - BAD_FILES=$(gofmt -l .) && [[ -z "${BAD_FILES}" ]] || (echo >&2 "Badly formatted files:" && echo "${BAD_FILES}" && exit 1)
  - go build
  - go test ./...
  - go tool vet .
